/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * pCreate.java
 *
 * Created on 13.02.2011, 0:08:30
 */

package start.gui;

import start.TestImg;

import javax.swing.*;
import java.awt.geom.*;
import java.awt.*;

/**
 * @author Евгений
 */
public class pCreate extends javax.swing.JPanel {

    /**
     * Creates new form pCreate
     */
    public pCreate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pQuery = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        pCreateProject = new javax.swing.JPanel();
        pModificateProject = new javax.swing.JPanel();
        pContPanel = new javax.swing.JPanel();
        pSteep = new javax.swing.JPanel(){ public void paintComponent(Graphics g) {
            super.paintComponent(g);
            // TestImg.getInstance().drawLeftPanel(g,this );
            //            g2d.dispose();
        }} ;
        pStep1 = new javax.swing.JPanel(){ public void paintComponent(Graphics g) {
            super.paintComponent(g);
            TestImg.getInstance().drawLabel(g,this);
            //            g2d.dispose();
        }} ;
        lSteep1 = new javax.swing.JLabel();
        pStep2 = new javax.swing.JPanel(){ public void paintComponent(Graphics g) {
            super.paintComponent(g);
            TestImg.getInstance().drawLabel(g,this);
            //            g2d.dispose();
        }} ;
        lSteep2 = new javax.swing.JLabel();
        pStep3 = new javax.swing.JPanel() { public void paintComponent(Graphics g) {
            super.paintComponent(g);
            TestImg.getInstance().drawLabel(g,this);
            //            g2d.dispose();
        }};
        lSteep3 = new javax.swing.JLabel();
        pStep4 = new javax.swing.JPanel(){ public void paintComponent(Graphics g) {
            super.paintComponent(g);
            TestImg.getInstance().drawLabel(g,this);
            //            g2d.dispose();
        }} ;
        lSteep4 = new javax.swing.JLabel();
        pStep5 = new javax.swing.JPanel() { public void paintComponent(Graphics g) {
            super.paintComponent(g);
            TestImg.getInstance().drawLabel(g,this);
            //            g2d.dispose();
        }};
        lSteep5 = new javax.swing.JLabel();
        pStep6 = new javax.swing.JPanel() { public void paintComponent(Graphics g) {
            super.paintComponent(g);
            TestImg.getInstance().drawLabel(g,this);
            //            g2d.dispose();
        }};
        lSteep6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pContener = new javax.swing.JPanel(){ public void paintComponent(Graphics g) {
            super.paintComponent(g);
            // TestImg.getInstance().drawContenerPanel(g, this);
        }};
        pCreateSpeciality = new javax.swing.JPanel(){ public void paintComponent(Graphics g) {
            super.paintComponent(g);
            //    TestImg.getInstance().drawDownPanel(g, this);

            //            g2d.dispose();
        }} ;
        jPanel5 = new javax.swing.JPanel(){
            public void paintComponent(Graphics g) {
                super.paintComponent(g);
                //        TestImg.getInstance().drawDownPanel(g, this);

                //            g2d.dispose();
            }
        };
        bAddSpeciality = new javax.swing.JButton();
        bEditSpeciality = new javax.swing.JButton();
        bRemoveSpeciality = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tSpeciality = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pCreateTask = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        bAddTask = new javax.swing.JButton();
        bEditTask = new javax.swing.JButton();
        bRemoveTask = new javax.swing.JButton();
        bGenerateTask = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tTask = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pCreateExecutor = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        bAddExecutor = new javax.swing.JButton();
        bEditExecutor = new javax.swing.JButton();
        bRemoveExecutor = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tExecutor = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pCreateDependens = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        pCreateTaskForExecutor = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        treeExecutors = new javax.swing.JTree();
        jPanel8 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        bLeft = new javax.swing.JButton();
        bRight = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        listTasks = new javax.swing.JList();
        pViewStructure = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        pCont = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel(){
            public void paintComponent(Graphics g) {
                super.paintComponent(g);
                TestImg.getInstance().drawDownPanel(g, this);

                //            g2d.dispose();
            }
        } ;
        bMain = new javax.swing.JButton();
        bPrevious = new javax.swing.JButton();
        bNext = new javax.swing.JButton();
        bMake = new javax.swing.JButton();

        pQuery.setLayout(new java.awt.BorderLayout(2, 2));

        jPanel15.setBackground(new java.awt.Color(255, 255, 204));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.orange));
        jPanel15.setPreferredSize(new java.awt.Dimension(647, 104));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );

        pQuery.add(jPanel15, java.awt.BorderLayout.NORTH);

        jPanel16.setPreferredSize(new java.awt.Dimension(647, 300));
        jPanel16.setLayout(new java.awt.BorderLayout());

        jPanel17.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 15));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel1.setText("Выбериье тип проекта:");
        jPanel17.add(jLabel1);

        jPanel16.add(jPanel17, java.awt.BorderLayout.NORTH);

        jPanel18.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 70, 20));

        jPanel19.setPreferredSize(new java.awt.Dimension(348, 100));
        jPanel19.setLayout(new java.awt.GridLayout(2, 0));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 14));
        jRadioButton2.setSelected(true);
        jRadioButton2.setText(" проект синтеза");
        jRadioButton2.setPreferredSize(new java.awt.Dimension(107, 55));
        jPanel19.add(jRadioButton2);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jRadioButton1.setText(" проект анализа и совершенствования");
        jPanel19.add(jRadioButton1);

        jPanel18.add(jPanel19);

        jPanel16.add(jPanel18, java.awt.BorderLayout.CENTER);

        pQuery.add(jPanel16, java.awt.BorderLayout.CENTER);

        pCreateProject.setBackground(new java.awt.Color(233, 229, 229));
        pCreateProject.setLayout(new javax.swing.BoxLayout(pCreateProject, javax.swing.BoxLayout.LINE_AXIS));

        pModificateProject.setLayout(new javax.swing.BoxLayout(pModificateProject, javax.swing.BoxLayout.LINE_AXIS));

        pContPanel.setBackground(new java.awt.Color(233, 229, 229));
        pContPanel.setMaximumSize(new java.awt.Dimension(10000, 32767));
        pContPanel.setMinimumSize(new java.awt.Dimension(0, 90));
        pContPanel.setPreferredSize(new java.awt.Dimension(910, 840));
        pContPanel.setLayout(new java.awt.BorderLayout());

        pSteep.setBackground(new java.awt.Color(255, 255, 255));
        pSteep.setMaximumSize(new java.awt.Dimension(254, 150));
        pSteep.setMinimumSize(new java.awt.Dimension(240, 0));
        pSteep.setPreferredSize(new java.awt.Dimension(254, 588));
        pSteep.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        pStep1.setMaximumSize(new java.awt.Dimension(250, 30));
        pStep1.setMinimumSize(new java.awt.Dimension(250, 30));
        pStep1.setPreferredSize(new java.awt.Dimension(250, 30));
        pStep1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lSteep1.setFont(new java.awt.Font("Tahoma", 1, 13));
        lSteep1.setForeground(new java.awt.Color(255, 51, 51));
        lSteep1.setText("   1. Cпециализации");
        pStep1.add(lSteep1);

        pSteep.add(pStep1);

        pStep2.setMaximumSize(new java.awt.Dimension(250, 30));
        pStep2.setMinimumSize(new java.awt.Dimension(250, 30));
        pStep2.setPreferredSize(new java.awt.Dimension(250, 30));
        pStep2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lSteep2.setText("   2. Задачи");
        pStep2.add(lSteep2);

        pSteep.add(pStep2);

        pStep3.setMaximumSize(new java.awt.Dimension(250, 30));
        pStep3.setMinimumSize(new java.awt.Dimension(250, 30));
        pStep3.setPreferredSize(new java.awt.Dimension(250, 30));
        pStep3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lSteep3.setText("   3. Исполнители");
        pStep3.add(lSteep3);

        pSteep.add(pStep3);

        pStep4.setMaximumSize(new java.awt.Dimension(250, 30));
        pStep4.setMinimumSize(new java.awt.Dimension(250, 30));
        pStep4.setPreferredSize(new java.awt.Dimension(250, 30));
        pStep4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lSteep4.setText("   4. Построение структуры");
        pStep4.add(lSteep4);

        pSteep.add(pStep4);

        pStep5.setMaximumSize(new java.awt.Dimension(250, 30));
        pStep5.setMinimumSize(new java.awt.Dimension(250, 30));
        pStep5.setPreferredSize(new java.awt.Dimension(250, 30));
        pStep5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lSteep5.setText("   5. Назначение задач");
        pStep5.add(lSteep5);

        pSteep.add(pStep5);

        pStep6.setMaximumSize(new java.awt.Dimension(250, 30));
        pStep6.setMinimumSize(new java.awt.Dimension(250, 30));
        pStep6.setPreferredSize(new java.awt.Dimension(250, 30));
        pStep6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lSteep6.setText("   3. Структура управления");
        pStep6.add(lSteep6);

        pSteep.add(pStep6);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pSteep.add(jPanel1);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/1234.png"))); // NOI18N
        pSteep.add(jLabel2);

        pContPanel.add(pSteep, java.awt.BorderLayout.WEST);

        pContener.setMinimumSize(new java.awt.Dimension(727, 90));
        pContener.setPreferredSize(new java.awt.Dimension(730, 840));
        pContener.setLayout(new java.awt.CardLayout(2, 5));

        pCreateSpeciality.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        pCreateSpeciality.setLayout(new java.awt.BorderLayout(2, 2));

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        bAddSpeciality.setText("Добавить специализацию");
        jPanel5.add(bAddSpeciality);

        bEditSpeciality.setText("Редактировать специализацию");
        jPanel5.add(bEditSpeciality);

        bRemoveSpeciality.setText("Удалить специализацию");
        jPanel5.add(bRemoveSpeciality);

        pCreateSpeciality.add(jPanel5, java.awt.BorderLayout.SOUTH);

        tSpeciality.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tSpeciality);

        pCreateSpeciality.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel7.setBackground(TestImg.getInstance().getColorInfPanel());
        jPanel7.setBorder(new javax.swing.border.LineBorder(java.awt.Color.orange, 1, true));
        jPanel7.setPreferredSize(new java.awt.Dimension(647, 104));

        jLabel4.setText("Такст");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(338, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(275, 275, 275))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel4)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pCreateSpeciality.add(jPanel7, java.awt.BorderLayout.NORTH);

        pContener.add(pCreateSpeciality, "card2");

        pCreateTask.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        pCreateTask.setLayout(new java.awt.BorderLayout(2, 2));

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        bAddTask.setText("Добавить задачу");
        jPanel6.add(bAddTask);

        bEditTask.setText("Редактировать задачу");
        bEditTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditTaskActionPerformed(evt);
            }
        });
        jPanel6.add(bEditTask);

        bRemoveTask.setText("Удалить задачу");
        bRemoveTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRemoveTaskActionPerformed(evt);
            }
        });
        jPanel6.add(bRemoveTask);

        bGenerateTask.setBackground(new java.awt.Color(153, 204, 255));
        bGenerateTask.setText("Синтезировать структуру");
        bGenerateTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGenerateTaskActionPerformed(evt);
            }
        });
        jPanel6.add(bGenerateTask);

        pCreateTask.add(jPanel6, java.awt.BorderLayout.SOUTH);

        tTask.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tTask);

        pCreateTask.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel9.setBackground(TestImg.getInstance().getColorInfPanel());
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.orange));
        jPanel9.setPreferredSize(new java.awt.Dimension(647, 104));

        jLabel5.setText("Такст");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(344, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(275, 275, 275))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel5)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pCreateTask.add(jPanel9, java.awt.BorderLayout.NORTH);

        pContener.add(pCreateTask, "card2");

        pCreateExecutor.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        pCreateExecutor.setLayout(new java.awt.BorderLayout(2, 2));

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        bAddExecutor.setText("Добавить исполнителя");
        jPanel10.add(bAddExecutor);

        bEditExecutor.setText("Редактировать исполнителя");
        jPanel10.add(bEditExecutor);

        bRemoveExecutor.setText("Удалить исполнителя");
        bRemoveExecutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRemoveExecutorActionPerformed(evt);
            }
        });
        jPanel10.add(bRemoveExecutor);

        pCreateExecutor.add(jPanel10, java.awt.BorderLayout.SOUTH);

        tExecutor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tExecutor);

        pCreateExecutor.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel11.setBackground(TestImg.getInstance().getColorInfPanel());
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.orange));
        jPanel11.setPreferredSize(new java.awt.Dimension(647, 104));

        jLabel6.setText("Такст");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(338, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(275, 275, 275))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel6)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pCreateExecutor.add(jPanel11, java.awt.BorderLayout.NORTH);

        pContener.add(pCreateExecutor, "card2");

        pCreateDependens.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        pCreateDependens.setLayout(new java.awt.BorderLayout(2, 2));

        jPanel13.setBackground(TestImg.getInstance().getColorInfPanel());
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.orange));
        jPanel13.setPreferredSize(new java.awt.Dimension(647, 104));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );

        pCreateDependens.add(jPanel13, java.awt.BorderLayout.NORTH);

        pContener.add(pCreateDependens, "card2");

        pCreateTaskForExecutor.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        pCreateTaskForExecutor.setLayout(new java.awt.BorderLayout(2, 2));

        jPanel14.setBackground(TestImg.getInstance().getColorInfPanel()
        );
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.orange));
        jPanel14.setPreferredSize(new java.awt.Dimension(647, 104));

        jLabel8.setText("kmcjkiwemjcikwec");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(265, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(275, 275, 275))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel8)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pCreateTaskForExecutor.add(jPanel14, java.awt.BorderLayout.NORTH);

        jScrollPane4.setViewportView(treeExecutors);

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.Y_AXIS));

        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.Y_AXIS));

        jPanel20.setMaximumSize(new java.awt.Dimension(32767, 20));
        jPanel20.setPreferredSize(new java.awt.Dimension(5, 10));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel12.add(jPanel20);

        bLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/1.png"))); // NOI18N
        jPanel12.add(bLeft);

        bRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/0.png"))); // NOI18N
        jPanel12.add(bRight);

        jPanel8.add(jPanel12);

        listTasks.setModel(new DefaultListModel() );
        jScrollPane5.setViewportView(listTasks);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pCreateTaskForExecutor.add(jPanel4, java.awt.BorderLayout.CENTER);

        pContener.add(pCreateTaskForExecutor, "card6");

        pViewStructure.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        pViewStructure.setLayout(new java.awt.BorderLayout(2, 2));

        jPanel21.setBackground(TestImg.getInstance().getColorInfPanel());
        jPanel21.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.orange));
        jPanel21.setPreferredSize(new java.awt.Dimension(647, 104));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );

        pViewStructure.add(jPanel21, java.awt.BorderLayout.NORTH);

        pContener.add(pViewStructure, "card2");

        pContPanel.add(pContener, java.awt.BorderLayout.CENTER);

        pModificateProject.add(pContPanel);

        setBackground(new java.awt.Color(233, 229, 229));
        setLayout(new java.awt.BorderLayout(4, 4));

        pCont.setBackground(new java.awt.Color(51, 102, 0));
        pCont.setLayout(new javax.swing.BoxLayout(pCont, javax.swing.BoxLayout.LINE_AXIS));
        add(pCont, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        bMain.setText("На главную");
        jPanel2.add(bMain);

        bPrevious.setText("Назад");
        jPanel2.add(bPrevious);

        bNext.setText("Далее");
        jPanel2.add(bNext);

        bMake.setText("Готово");
        bMake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMakeActionPerformed(evt);
            }
        });
        jPanel2.add(bMake);

        add(jPanel2, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void bEditTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditTaskActionPerformed
  
    }//GEN-LAST:event_bEditTaskActionPerformed

    private void bRemoveExecutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRemoveExecutorActionPerformed

}//GEN-LAST:event_bRemoveExecutorActionPerformed

    private void bMakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bMakeActionPerformed

    private void bGenerateTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGenerateTaskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bGenerateTaskActionPerformed

    private void bRemoveTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRemoveTaskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bRemoveTaskActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAddExecutor;
    private javax.swing.JButton bAddSpeciality;
    private javax.swing.JButton bAddTask;
    private javax.swing.JButton bEditExecutor;
    private javax.swing.JButton bEditSpeciality;
    private javax.swing.JButton bEditTask;
    private javax.swing.JButton bGenerateTask;
    private javax.swing.JButton bLeft;
    private javax.swing.JButton bMain;
    private javax.swing.JButton bMake;
    private javax.swing.JButton bNext;
    private javax.swing.JButton bPrevious;
    private javax.swing.JButton bRemoveExecutor;
    private javax.swing.JButton bRemoveSpeciality;
    private javax.swing.JButton bRemoveTask;
    private javax.swing.JButton bRight;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lSteep1;
    private javax.swing.JLabel lSteep2;
    private javax.swing.JLabel lSteep3;
    private javax.swing.JLabel lSteep4;
    private javax.swing.JLabel lSteep5;
    private javax.swing.JLabel lSteep6;
    private javax.swing.JList listTasks;
    private javax.swing.JPanel pCont;
    public javax.swing.JPanel pContPanel;
    private javax.swing.JPanel pContener;
    private javax.swing.JPanel pCreateDependens;
    private javax.swing.JPanel pCreateExecutor;
    private javax.swing.JPanel pCreateProject;
    private javax.swing.JPanel pCreateSpeciality;
    private javax.swing.JPanel pCreateTask;
    private javax.swing.JPanel pCreateTaskForExecutor;
    public javax.swing.JPanel pModificateProject;
    private javax.swing.JPanel pQuery;
    public javax.swing.JPanel pSteep;
    public javax.swing.JPanel pStep1;
    public javax.swing.JPanel pStep2;
    public javax.swing.JPanel pStep3;
    public javax.swing.JPanel pStep4;
    public javax.swing.JPanel pStep5;
    public javax.swing.JPanel pStep6;
    private javax.swing.JPanel pViewStructure;
    private javax.swing.JTable tExecutor;
    private javax.swing.JTable tSpeciality;
    private javax.swing.JTable tTask;
    private javax.swing.JTree treeExecutors;
    // End of variables declaration//GEN-END:variables

    public JButton getbAddExecutor() {
        return bAddExecutor;
    }

    public JButton getbAddSpeciality() {
        return bAddSpeciality;
    }

    public JButton getbAddTask() {
        return bAddTask;
    }

    public JButton getbEditExecutor() {
        return bEditExecutor;
    }

    public JButton getbEditSpeciality() {
        return bEditSpeciality;
    }

    public JButton getbEditTask() {
        return bEditTask;
    }

    public JButton getbMain() {
        return bMain;
    }

    public JButton getbNext() {
        return bNext;
    }

    

    public JButton getbPrevious() {
        return bPrevious;
    }

    public JButton getbRemoveExecutor() {
        return bRemoveExecutor;
    }

    public JButton getbRemoveSpeciality() {
        return bRemoveSpeciality;
    }

    public JButton getbRemoveTask() {
        return bRemoveTask;
    }

    public JPanel getpCreateExecutor() {
        return pCreateExecutor;
    }

    public JPanel getpCreateSpeciality() {
        return pCreateSpeciality;
    }

    public JPanel getpCreateTask() {
        return pCreateTask;
    }

    public JPanel getpSteep() {
        return pSteep;
    }

    public JPanel getpCreateTaskForExecutor() {
        return pCreateTaskForExecutor;
    }

    public JTable gettExecutor() {
        return tExecutor;
    }

    public JTable gettSpeciality() {
        return tSpeciality;
    }

    public JTable gettTask() {
        return tTask;
    }

    public JPanel getpContener() {
        return pContener;
    }

    public JLabel getLSteep1() {
        return lSteep1;
    }

    public JLabel getLSteep2() {
        return lSteep2;
    }


    public JLabel getLSteep3() {
        return lSteep3;
    }

    public JLabel getLSteep4() {
        return lSteep4;
    }

    public JPanel getpCreateDependens() {
        return pCreateDependens;
    }

    public JLabel getLSteep5() {
        return lSteep5;
    }

    public JLabel getLSteep6() {
        return lSteep6;
    }

    public JTree getTreeExecutors() {
        return treeExecutors;
    }

    public JList getListTasks() {
        return listTasks;
    }

    public JButton getbLeft() {
        return bLeft;
    }

    public JButton getbRight() {
        return bRight;
    }
     public JButton getbMake() {
        return bMake;
    }

     public JButton getbGenerateTask() {
        return bGenerateTask;
    }

    public JPanel getpCont() {
        return pCont;
    }

    public JPanel getpQuery() {
        return pQuery;
    }

    public JPanel getpCreateProject() {
        return pCreateProject;
    }

    public JPanel getpModificateProject() {
        return pModificateProject;
    }

    public JPanel getpStep1() {
        return pStep1;
    }

    public JPanel getpStep2() {
        return pStep2;
    }

    public JPanel getpStep3() {
        return pStep3;
    }

    public JPanel getpStep4() {
        return pStep4;
    }

    public JPanel getpStep5() {
        return pStep5;
    }
        public JPanel getpStep6() {
        return pStep6;
    }


    
}
